version: 2

jobs:
  build:
    working_directory: /home/reaction

    docker:
      - image: node:7

    environment:
      - METEOR_ALLOW_SUPERUSER: true

    steps:
      - setup_remote_docker
      - checkout

      # install OS dependencies
      - restore_cache:
          key: meteor

      - run: .circleci/install.sh

      - save_cache:
          key: meteor
          paths:
            - ~/.meteor

      # install app dependencies
      - restore_cache:
          key: node_modules

      - run: meteor npm install

      - save_cache:
          key: node_modules
          paths:
            - /home/reaction/node_modules

      # run tests
      - run: reaction test
      - run: .circleci/build.sh

      # deploy the build (if on a deployment branch)
      - deploy:
          name: Docker Image Deploment
          command: .circleci/deploy.sh
